### ISSUE TITLE
worker-loader when main points to src/index.js

### ISSUE THREAD

**Issue by oyeanuj** [finalweb/image-worker#2]
Hi @jeremymlane, thank you for open sourcing this library. 

I noticed that the `main` in `package.json` is pointing to `src/index.js`. But with that, I kept getting errors that `worker-loader` module wasn't found. That made sense since it seemed to be a `devDependency`. 

Moving the `main` to  `dist/image-worker.js` seems to do the trick for that error but then results in a different error - that `ImageProcessor` isn't a constructor. 

Thoughts on how to solve this?

**Comment by jeremymlane** [comment]
@oyeanuj Three years later, this is fixed.
